version: '3'

services:

   prd:
     image: 10.1.0.60:8083/shark:prd
     deploy:
       labels:
         - "traefik.enable=true"
         - "traefik.docker.network=shark_prd"
         - "traefik.http.middlewares.shark-mid.redirectscheme.scheme=https"
         - "traefik.http.routers.shark-web.middlewares=shark-mid"
         - "traefik.http.routers.shark-web.rule=Host(`shark.alegra.com.br`)"
         - "traefik.http.routers.shark-web.entrypoints=web"
         - "traefik.http.routers.shark-websecure.rule=Host(`shark.alegra.com.br`)"
         - "traefik.http.routers.shark-websecure.service=shark-svc"
         - "traefik.http.services.shark-svc.loadbalancer.server.port=80"
         - "traefik.http.routers.shark-websecure.entrypoints=websecure"
         - "traefik.http.routers.shark-websecure.tls.certresolver=myresolver"
         - "traefik.http.routers.shark-websecure.tls=true"
       mode: replicated
       replicas: 1
       restart_policy:
         condition: on-failure
         delay: 3s
     networks:
       - prd

   traefik:
     image: traefik:2.3
     ports:
       - "80:80"
       - "9081:8080"
       - "443:443"
     deploy:
      mode: global
      placement:
        constraints: [node.role==manager]
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /opt/ssl/acme.json:/acme.json
       - /opt/ssl/traefik.toml:/traefik.toml
     networks:
       - prd
       - dev
       - qas

networks:
  prd:
  qas:
  dev: